// Date: 11/11/2013 2:25:49 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package LightProcessing.resources.mods.ltp.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMachineCore extends ModelBase
{
  //fields
    public static ModelRenderer Gear11;
    public static ModelRenderer Gear12;
    ModelRenderer Base;
    public static ModelRenderer Axel;
    public static ModelRenderer Gear21;
    public static ModelRenderer Gear22;
    ModelRenderer Top;
    ModelRenderer Beam1;
    ModelRenderer Beam2;
    ModelRenderer Beam3;
    ModelRenderer Beam4;
  static float y = 0.0F;
  public ModelMachineCore()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Gear11 = new ModelRenderer(this, 0, 0);
      Gear11.addBox(-4F, -2F, -4F, 8, 2, 8);
      Gear11.setRotationPoint(0F, 11F, 0F);
      Gear11.setTextureSize(64, 64);
      Gear11.mirror = true;
      setRotation(Gear11, 0F, 3.141593F, 0F);
      Gear12 = new ModelRenderer(this, 31, 0);
      Gear12.addBox(-4F, -2F, -4F, 8, 2, 8);
      Gear12.setRotationPoint(0F, 11F, 0F);
      Gear12.setTextureSize(64, 64);
      Gear12.mirror = true;
      setRotation(Gear12, 0F, 2.356194F, 0F);
      Base = new ModelRenderer(this, 0, 47);
      Base.addBox(-8F, 0F, -8F, 16, 1, 16);
      Base.setRotationPoint(0F, 23F, 0F);
      Base.setTextureSize(64, 64);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Axel = new ModelRenderer(this, 4, 16);
      Axel.addBox(-1F, 0F, -1F, 2, 10, 2);
      Axel.setRotationPoint(0F, 11F, 0F);
      Axel.setTextureSize(64, 64);
      Axel.mirror = true;
      setRotation(Axel, 0F, 2.356194F, 0F);
      Gear21 = new ModelRenderer(this, 0, 0);
      Gear21.addBox(-4F, -1F, -4F, 8, 2, 8);
      Gear21.setRotationPoint(0F, 22F, 0F);
      Gear21.setTextureSize(64, 64);
      Gear21.mirror = true;
      setRotation(Gear21, 0F, 2.356194F, 0F);
      Gear22 = new ModelRenderer(this, 31, 0);
      Gear22.addBox(-4F, -1F, -4F, 8, 2, 8);
      Gear22.setRotationPoint(0F, 22F, 0F);
      Gear22.setTextureSize(64, 64);
      Gear22.mirror = true;
      setRotation(Gear22, 0F, 3.141593F, 0F);
      Top = new ModelRenderer(this, 0, 47);
      Top.addBox(-8F, 0F, -8F, 16, 1, 16);
      Top.setRotationPoint(0F, 8F, 0F);
      Top.setTextureSize(64, 64);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
      Beam1 = new ModelRenderer(this, 0, 16);
      Beam1.addBox(0F, 0F, 0F, 1, 14, 1);
      Beam1.setRotationPoint(7F, 9F, -8F);
      Beam1.setTextureSize(64, 64);
      Beam1.mirror = true;
      setRotation(Beam1, 0F, 0F, 0F);
      Beam2 = new ModelRenderer(this, 0, 16);
      Beam2.addBox(0F, 0F, 0F, 1, 14, 1);
      Beam2.setRotationPoint(-8F, 9F, -8F);
      Beam2.setTextureSize(64, 64);
      Beam2.mirror = true;
      setRotation(Beam2, 0F, 0F, 0F);
      Beam3 = new ModelRenderer(this, 0, 16);
      Beam3.addBox(0F, 0F, 0F, 1, 14, 1);
      Beam3.setRotationPoint(7F, 9F, 7F);
      Beam3.setTextureSize(64, 64);
      Beam3.mirror = true;
      setRotation(Beam3, 0F, 0F, 0F);
      Beam4 = new ModelRenderer(this, 0, 16);
      Beam4.addBox(0F, 0F, 0F, 1, 14, 1);
      Beam4.setRotationPoint(-8F, 9F, 7F);
      Beam4.setTextureSize(64, 64);
      Beam4.mirror = true;
      setRotation(Beam4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Gear11.render(f5);
    Gear12.render(f5);
    Base.render(f5);
    Axel.render(f5);
    Gear21.render(f5);
    Gear22.render(f5);
    Top.render(f5);
    Beam1.render(f5);
    Beam2.render(f5);
    Beam3.render(f5);
    Beam4.render(f5);
  }
  
  public static void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public static void addRotation(ModelRenderer model, float x, float y, float z)
  {
	  	model.rotateAngleX = model.rotateAngleX + x;
	    model.rotateAngleY = model.rotateAngleY + y;
	    model.rotateAngleZ = model.rotateAngleZ + z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

  public static void rotate(){
	  y += 0.05F;
		ModelMachineCore.setRotation(ModelMachineCore.Axel, 0.0F, y, 0.0F);
		ModelMachineCore.setRotation(ModelMachineCore.Gear11, 0.0F, y, 0.0F);
		ModelMachineCore.setRotation(ModelMachineCore.Gear12, 0.0F, y + 0.8F, 0.0F);
		ModelMachineCore.setRotation(ModelMachineCore.Gear21, 0.0F, y, 0.0F);
		ModelMachineCore.setRotation(ModelMachineCore.Gear22, 0.0F, y + 0.8F, 0.0F);
  }
  
}
